### ISSUE TITLE
Any new release soon?

### ISSUE THREAD

**Issue by LeonorLunatech** [BenFradet/spark-kafka-writer#146]
Hi Ben, I have noticed that this dependency is used on a project and that the last released version is very outdated. I have  also noticed that the codebase has evolved since. Are you planning on doing a release any time soon?

**Comment by BenFradet** [comment]
hey! yes, I'll try to publish 0.5.0 tomorrow :+1:

**Comment by BenFradet** [comment]
I just released it, hopefully it will appear on central during the day :+1:
