### ISSUE TITLE
Could you clarify meaning of installation section?

### ISSUE THREAD

**Issue by TokyoMike** [BenFradet/spark-kafka-writer#151]
In the installation section it reads 

`spark-kafka-writer is available on maven central with the following coordinates depending on whether you're using Kafka 0.8 or 0.10 and your version of Spark:`

and uses the following syntax to describe the appropriate jar to download.  Could you clarify the meaning of this in detail, as I don't understand the below notation?

`"com.github.benfradet" %% "spark-kafka-0-10-writer" % "0.3.0"`

**Comment by BenFradet** [comment]
yes, this is the SBT notation:

- `com.github.benfradet` is the org
- `spark-kafka-0-10-writer` is the artifact (it gets resolved to `spark-kafka-writer-0-10-writer_2.11` by SBT depending on your scala version)
- `0.3.0` is the version
