### ISSUE TITLE
Kafka 0.10.x and Spark 1.6.x

### ISSUE THREAD

**Issue by ecesena** [BenFradet/spark-kafka-writer#34]
Could you elaborate on the missing support for Kafka 0.10.x on Spark 1.6.x? Is this something just currently not supported, or are there major issues?

We are currently running Spark 1.6.x with Kafka 0.9 (using the previous versions of spark-kaka-writer released by cloudera). We're in the process of upgrading first to Kafka 0.10, and only later to Spark 2.x, so I'd be interested in this combination to keep my system up and running.

Thank you much! E.

**Comment by BenFradet** [comment]
Ideally, it should be working since there hasn't been any change regarding the producer API but I haven't tested it personally.

I'd be glad to hear your feedback if you try it out.

**Comment by ecesena** [comment]
Glad to hear that - I'll test and let you know, thanks!

**Comment by ecesena** [comment]
Sorry for the delay, got lost in recompiling tons of things against Kafka 0.10.1.0.

This works great! I tried with Kafka 0.10.1.0 and Spark 1.6.0-CDH5.7 (manually recompiled to link against Kafka 0.10.1.0, otherwise it doesn't work).

**Comment by BenFradet** [comment]
Thanks for the feedback.
As a result, I think I'm gonna update the readme to reflect your findings, thanks again!
