### ISSUE TITLE
Exception:Topic cannot be null only in cluster mode 

### ISSUE THREAD

**Issue by shukla2009** [BenFradet/spark-kafka-writer#35]
I am trying this library and found one issue with this as its not able to find the output topic in cluster mode

`private def createJob(ssc: StreamingContext, kafkaParams: Map[String, String], intopics: Set[String],out:String) = {
    val stream = KafkaUtils
      .createDirectStream[String, String, StringDecoder, StringDecoder](ssc, kafkaParams, intopics)
    import spark.implicits._`

    `stream.
      foreachRDD(rdd => {
        if (!rdd.isEmpty()) {
          val rawDF = rdd.map(row => Sales(row._2)).toDF()
          val joinedRdd = rawDF.join(staticTables.get(tablesToJoin.head.name).get, tablesToJoin.head.joinColumn)
            .join(staticTables.get(tablesToJoin(1).name).get, tablesToJoin(1).joinColumn)
            .select(job.outColunms.head, job.outColunms.tail: _*).toJSON.rdd
          joinedRdd.writeToKafka(producerConfig, s => new ProducerRecord[String, String](out, s))
        }
      })
  }`

It works well in standalone mode

**Comment by BenFradet** [comment]
Where does `out` come from?

**Comment by shukla2009** [comment]
Out is coming from function param.. Let me paste full code

**Comment by shukla2009** [comment]
if I hard code the topic name like 
`joinedRdd.writeToKafka(producerConfig, s => new ProducerRecord[String, String]("outTopic", s))`
It starts working.


Even if I do println a line before `println("OUTPUTTOPIC =>"+out)` it prints the topic name
.

**Comment by BenFradet** [comment]
I know I had a few issues when inheriting the topic name from a trait maybe it's related.
It was because it didn't get shipped off with the lambda but I never found out why unfortunately.

**Comment by BenFradet** [comment]
Closing
