### ISSUE TITLE
When I use the spark sending messages are always multiple output a few pieces of information

### ISSUE THREAD

**Issue by EatMedicineFeelLovely** [BenFradet/spark-kafka-writer#40]
like this：(Article four the is not my hair)
Verifying properties
Property group.id is overridden to test
Property serializer.class is not valid
Property zookeeper.connect is overridden to zookeeper1
Hello,World
Hello,World
Hello,World
Hello,World
Hello,World
Hello,World

**Comment by BenFradet** [comment]
I'm not sure I understand your question, could you make it a bit clearer please?

**Comment by EatMedicineFeelLovely** [comment]
my code is : 
producer.send("Hello World！")
but 
The output of consumption like this：
[
Verifying properties
Property group.id is overridden to test
Property serializer.class is not valid
Property zookeeper.connect is overridden to solr2.zhiziyun.com,solr1.zhiziyun.com,mongodb3
Verifying properties
Verifying properties
Property group.id is overridden to test
Property serializer.class is not valid
Property group.id is overridden to test
Property zookeeper.connect is overridden to solr2.zhiziyun.com,solr1.zhiziyun.com,mongodb3
Property serializer.class is not valid
Hello World！
Hello World！
Hello World！
]

**Comment by BenFradet** [comment]
Do you have 3 elements in your RDD?

**Comment by EatMedicineFeelLovely** [comment]
yes!
my question is :
Why do I have ：
“Verifying properties
Property group.id is overridden to test
Property serializer.class is not valid
Property zookeeper.connect is overridden to solr2.zhiziyun.com,solr1.zhiziyun.com,mongodb3”

**Comment by BenFradet** [comment]
It's just debugging done by kafka when you launch your consumer https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/utils/VerifiableProperties.scala#L217-L226

**Comment by EatMedicineFeelLovely** [comment]
But I have this information when I consume data. This is not a log message

**Comment by EatMedicineFeelLovely** [comment]
If I don't use spark to send messages.No problem

**Comment by EatMedicineFeelLovely** [comment]
It can be consumed like 'Hello, world'

**Comment by BenFradet** [comment]
Whenever you'll consume or produce messages you'll see these logging information if your log level is INFO or DEBUG, it's just the way it is.

**Comment by EatMedicineFeelLovely** [comment]
So how should I modify my log level

**Comment by BenFradet** [comment]
Have a look at:

- https://www.mkyong.com/logging/log4j-log4j-properties-examples/
- http://stackoverflow.com/questions/28454080/how-to-log-using-log4j-to-local-file-system-inside-a-spark-application-that-runs

**Comment by EatMedicineFeelLovely** [comment]
This log is spark log configuration
If my topic is test
When I consume information, I get the following:
(test,Verifying properties)
(test,Property group.id is overridden to test)
(test,Property serializer.class is not valid)

**Comment by BenFradet** [comment]
Then you're not producing the right information, assuming you have a RDD of String called rdd:

```scala
rdd.writeToKafka(
  producerConfig,
  s => new ProducerRecord[String, String](topic, s)
)
```

**Comment by EatMedicineFeelLovely** [comment]
This is my code :
rdd.writeToKafka(producerConfig,s=>new ProducerRecord[String, String]("test", "Hello,world"))

**Comment by EatMedicineFeelLovely** [comment]
I have solved this problem, Thanks anyway
This is due to a jar package

**Comment by BenFradet** [comment]
Ok great, closing.
