### ISSUE TITLE
Provide a way to close producers

### ISSUE THREAD

**Issue by nightscape** [BenFradet/spark-kafka-writer#42]
Hi @BenFradet,

we are currently experimenting with `spark-kafka-writer` and also using it in our tests.
In the tests, we need to `close` all producers, otherwise we get bombarded by
```
java.net.ConnectException: Connection refused
```
The `KafkaProducerCache` already [memoizes the created producers](https://github.com/BenFradet/spark-kafka-writer/blob/master/spark-kafka-0-8-writer/src/main/scala/com/github/benfradet/spark/kafka08/writer/KafkaProducerCache.scala#L32) which could be used for closing all producers, but unfortunately both the class and the field are private.
We're working around that by creating another class in the same package and accessing the `producers` field via reflection, but that is a rather ugly and dangerous option.

What do you think about making the `KafkaProducerCache` public and either exposing the `producers` field, or providing a method like
```scala
def allProducers = producers.values
```
which does not allow modification, but could be used like this
```scala
KafkaProducerCache.allProducers.foreach(_.close)
```

**Comment by BenFradet** [comment]
It seems to be a good idea.

Making things public and adding `allProcuers` would be one way to do it. How do you feel about a shutdown hook?

**Comment by nightscape** [comment]
If by shutdown hook you mean a [JVM shutdown hook](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)), that wouldn't be sufficient in our case as we went to run multiple "blank slate" tests before shutting down the JVM.
Or did you mean a method like `KafkaProducerCache.closeAll`? That indeed would solve our use case :+1:

**Comment by BenFradet** [comment]
I indeed meant a jvm shutdown hook.

The problem I see with exposing the producers in `KafkaProducerCache` is that it really seems ad hoc plus you would need to close those producers in a closure which seems a bit clunky to me.

**Comment by nightscape** [comment]
Ok, then maybe best stick with the `KafkaProducerCache.closeAll` method?

**Comment by BenFradet** [comment]
hey @nightscape Sorry I haven't gotten back to you earlier.

I did give some thought to this however and what do you think of having a `close` method like so:

```scala
def close(producerConfig: Properties): Unit = ???
```

which closes the producer which has `producerConfig` as key in the `producers` map?

**Comment by nightscape** [comment]
That would work for us :+1:

**Comment by BenFradet** [comment]
Feel free to open a PR! Otherwise, I'll try to incorporate it to the next release.

**Comment by BenFradet** [comment]
For future reference, this should follow an implementation similar to apache/spark#17308
