### ISSUE TITLE
Releases 0.2.0 and 0.3.0 missing from Maven Central

### ISSUE THREAD

**Issue by cosminci** [BenFradet/spark-kafka-writer#88]
Since 0.4.0 is not backward compatible with Spark 2.0.x or Spark 2.1.x, this is quite important.

**Comment by BenFradet** [comment]
what do you mean? 0.2.0 and 0.3.0 are on maven central: http://search.maven.org/#search|gav|1|g%3A"com.github.benfradet"%20AND%20a%3A"spark-kafka-0-10-writer_2.11"

**Comment by cosminci** [comment]
Just noticed the artefact name contains the Kafka version for 0.2.0 and 0.3.0.

I was just switching the version and only getting:
https://mvnrepository.com/artifact/com.github.benfradet/spark-kafka-writer_2.11

Thanks!

**Comment by BenFradet** [comment]
Yup I decided to stop supportting kafka 0.8 since not a lot of people were using it.
