### ISSUE TITLE
When will Kafka 1.0.0 support will be released?

### ISSUE THREAD

**Issue by noorul** [BenFradet/spark-kafka-writer#92]

**Comment by BenFradet** [comment]
is kafka 1.0.1 supported in Spark?

**Comment by AleksandarIvanov7887** [comment]
Hi @BenFradet , Spark is still only supporting up until kafka-0.10.
From what I understand, this library (kafka-writer) is dependent on the 'spark-streaming-kafka-0-10' only for testing, to read the results from writing.
I have tried bumping the kafka version to 2.3.0 and the unit tests, after some small adjustments, seem to run fine.
Do you think that it is appropriate to increase the kafka version along with the scala version ?

**Comment by BenFradet** [comment]
I think so, definitely :+1:

I think the original concern was around aligning the kafka versions on the classpath when using this library together with `spark-streaming-kafka-0-10`.

**Comment by BenFradet** [comment]
done, closing
